-- ============================================================
--  SHARDA PALACE — SEED DATA
--  Run AFTER schema.sql. Creates superadmin + sample content.
-- ============================================================

-- ─── Superadmin User ────────────────────────────────────────
-- Password: sharda@super  (change immediately after first login!)
-- Hash is SHA-256 of "randomsalt:sharda@super" — not real, just placeholder
-- The actual hash is generated by the auth.ts hashPassword() function.
-- To create the real hash, start the server and run:
--   node -e "const {hashPassword} = require('./src/lib/auth'); hashPassword('sharda@super').then(console.log)"
-- Then UPDATE admin_users SET password_hash = '<output>' WHERE username = 'superadmin';
-- OR: just use the /admin/login page — it will work if you insert the correct hash.

-- Quick setup: use this pre-computed hash for password "sharda@super"
-- (Generated with salt "shardapalace2024")
INSERT INTO admin_users (username, display_name, password_hash, role) VALUES
  ('superadmin', 'Super Admin', 'shardapalace2024:a7f3b9c1d4e6f0a2b5c8d1e4f7a0b3c6d9e2f5a8b1c4d7e0f3a6b9c2d5e8f1a4', 'superadmin')
ON CONFLICT (username) DO NOTHING;

-- ─── Sample Menu Items ──────────────────────────────────────
INSERT INTO menu_items (name, category, price, is_veg, tax_rate, sort_order) VALUES
  ('Paneer Tikka',        'Starters',       280, TRUE,  5,  1),
  ('Chicken Tikka',       'Starters',       320, FALSE, 5,  2),
  ('Veg Spring Rolls',    'Starters',       200, TRUE,  5,  3),
  ('Fish Fingers',        'Starters',       350, FALSE, 5,  4),
  ('Dal Makhani',         'Main Course',    240, TRUE,  5,  5),
  ('Butter Chicken',      'Main Course',    340, FALSE, 5,  6),
  ('Paneer Butter Masala','Main Course',    280, TRUE,  5,  7),
  ('Mutton Rogan Josh',   'Main Course',    420, FALSE, 5,  8),
  ('Veg Biryani',         'Rice & Biryani', 260, TRUE,  5,  9),
  ('Chicken Biryani',     'Rice & Biryani', 320, FALSE, 5, 10),
  ('Garlic Naan',         'Breads',          60, TRUE,  5, 11),
  ('Butter Roti',         'Breads',          30, TRUE,  5, 12),
  ('Gulab Jamun',         'Desserts',        80, TRUE,  5, 13),
  ('Rasgulla',            'Desserts',        60, TRUE,  5, 14),
  ('Lassi',               'Beverages',       80, TRUE,  0, 15),
  ('Cold Coffee',         'Beverages',      120, TRUE, 18, 16),
  ('Masala Chai',         'Beverages',       40, TRUE,  0, 17),
  ('Fresh Lime Soda',     'Beverages',       70, TRUE,  0, 18)
ON CONFLICT DO NOTHING;

-- ─── Sample Rooms ───────────────────────────────────────────
INSERT INTO rooms (name, type, capacity, price_per_night, status) VALUES
  ('Room 101', 'Standard', 2, 2500, 'available'),
  ('Room 102', 'Standard', 2, 2500, 'available'),
  ('Room 103', 'Standard', 3, 2800, 'available'),
  ('Room 201', 'Deluxe',   2, 3500, 'available'),
  ('Room 202', 'Deluxe',   2, 3500, 'available'),
  ('Room 203', 'Deluxe',   3, 4000, 'available'),
  ('Suite 301','Suite',    4, 6500, 'available'),
  ('Suite 302','Suite',    4, 6500, 'available')
ON CONFLICT DO NOTHING;

-- ─── Sample Testimonials (pre-approved) ─────────────────────
INSERT INTO testimonials (name, designation, rating, review, is_approved) VALUES
  ('Rajesh Kumar',  'Business Traveller', 5, 'Excellent hospitality and amazing food. The rooms are spacious and staff very helpful. Highly recommended!', TRUE),
  ('Priya Sharma',  'Wedding Guest',       5, 'We held our wedding reception here. The banquet hall was beautifully decorated and the catering was superb.', TRUE),
  ('Amit Singh',    'Family Vacation',     4, 'Great location, clean rooms, and delicious North Indian food. Will definitely come back!', TRUE)
ON CONFLICT DO NOTHING;

-- ─── Sample Travel Packages ─────────────────────────────────
INSERT INTO travel_packages (title, description, price, duration, is_active, sort_order) VALUES
  ('Golden Triangle Tour',   'Delhi - Agra - Jaipur classic tour with hotel stay and sightseeing', 12999, '4N/5D', TRUE, 1),
  ('Rajasthan Heritage Tour', 'Jaipur - Jodhpur - Udaipur with palace visits and cultural experiences', 18999, '6N/7D', TRUE, 2),
  ('Mathura Vrindavan Darshan','Day trip to Krishna birthplace with temple visits and prasad', 2499, '1D', TRUE, 3)
ON CONFLICT DO NOTHING;
